# Generated by Django 5.2.3 on 2025-07-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',)},
        ),
    ]
