# Generated by Django 5.2.3 on 2025-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
