# Generated by Django 5.2.3 on 2025-07-26 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_alter_project_options_alter_projectmember_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('source_type', models.CharField(choices=[('web_app', 'Web Application'), ('api', 'API Service'), ('db', 'Database'), ('server', 'Server/Infrastructure'), ('mobile_app', 'Mobile Application'), ('iot', 'IoT Device'), ('custom', 'Custom')], max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10)),
                ('api_key', models.CharField(editable=False, max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('TRACE', 'Trace'), ('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('raw_log', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logs.logsource')),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['source', 'timestamp'], name='log_source_timestamp_idx'), models.Index(fields=['level'], name='log_level_idx')],
            },
        ),
    ]
