# Generated by Django 5.2.3 on 2025-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('projects', '0006_alter_project_options_alter_projectmember_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsource',
            options={'ordering': ('-name', 'created')},
        ),
        migrations.AddField(
            model_name='logentry',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='logsource',
            unique_together={('project', 'name')},
        ),
    ]
