# Generated by Django 5.2.3 on 2025-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logsource_options_logentry_meta_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsource',
            name='api_key',
        ),
        migrations.AddField(
            model_name='logsource',
            name='api_key_hash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
    ]
