# Generated by Django 5.2.3 on 2025-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_logsource_api_key_logsource_api_key_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ('-created',), 'verbose_name': 'Log entry', 'verbose_name_plural': 'Log entries'},
        ),
        migrations.AlterField(
            model_name='logsource',
            name='source_type',
            field=models.CharField(choices=[('web_app', 'Web Application'), ('api', 'API Service'), ('db', 'Database'), ('server', 'Server/Infrastructure'), ('mobile_app', 'Mobile Application'), ('iot', 'IoT Device'), ('custom', 'Custom')], default='custom', max_length=25),
        ),
    ]
