# Generated by Django 5.2.3 on 2025-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
