# Generated by Django 5.2.3 on 2025-07-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_alter_organization_options_alter_orgmember_org_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orginvite',
            unique_together=set(),
        ),
    ]
